config/routes.rb
Rails.application.routes.draw do
  resources :categories, only: [:index, :show] do
    resources :movies, only: [:index, :show]
  end

  devise_for :users

  resources :movies, only: [:index, :show] do
    resources :reviews
  end

  resources :users, only: [:index, :show]
  resources :reviews, only: [:index]

  resources :review_votes, only: [:new, :create]

  root 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :movies
  has_many :reviews, through: :movies

  validates :name, :movie_db_id, presence: true
  validates :name, uniqueness: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :review
  belongs_to :commenter, class_name: 'User'

  validates :body, presence: true
  validates :review_id, presence: true
  validates :commenter_id, presence: true
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :category
  has_many :reviews

  validates :title, :poster_path, :summary, :release_date, :category_id, presence: true

  validates :title, uniqueness: true

  def self.search(search)
    search_param = search.downcase
    where("lower(title) LIKE ?", "%#{search_param}%")
  end

  scope :recent, -> { order('created_at DESC') }

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :movie
  belongs_to :reviewer, class_name: 'User'
  has_many :comments

  validates :title, presence: true
  validates :body, presence: true
  validates :stars, presence: true
  validates :reviewer_id, presence: true
  validates :movie_id, presence: true

  before_save :set_points

  scope :recent, -> { order('created_at DESC') }

  protected

  def set_points
    self.points ||= 0
  end
end

app/models/review_vote.rb
class ReviewVote < ActiveRecord::Base
  belongs_to :review
  belongs_to :voter, class_name: 'User'

  validates_uniqueness_of :voter_id, scope: :review_id
  validates :review_id, presence: true
  validates :voter_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews, foreign_key: 'reviewer_id'
  has_many :review_votes, foreign_key: 'voter_id'
  has_many :comments, foreign_key: 'commenter_id'

  before_save :set_default_values

  validates :username, presence: true
  # validates :email, presence: true
  # validates :password_digest, presence: true
  # validates :rating, presence: true
  # validates :status, presence: true

  def update_status
    if self.rating >= 40
      self.status = "Gold"
      self.save
    elsif self.rating >= 25
      self.status = "Silver"
      self.save
    elsif self.rating >= 10
      self.status = "Bronze"
      self.save
    else
      self.status = "Novice"
      self.save
    end
  end


  protected

  def set_default_values
    self.rating ||= 0
    self.status ||= "Novice"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index

    if params[:search]
      @movies = Movie.search(params[:search])
      if @movies.length > 0
        @movies
      else
        @errors = "No movies matched your search criteria"
      end
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

app/controllers/review_votes_controller.rb
class ReviewVotesController < ApplicationController

  def create

  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @movie = Movie.find_by(id: params[:movie_id])
    @review = Review.new
    if request.xhr?
      render :'reviews/_form', layout: false, locals: { review: @review }
    else
      render :new
    end
  end

  def create
    @review = Review.create(full_params)
    if @review.save
      render :'reviews/_show', layout: false, locals: { review: @review }
    else
      flash[:notice] = "Post successfully created"
      redirect_to category_movie_path
    end
  end

  private

  def full_params
    params.require(:review).permit(:title, :body, :movie_id, :stars, :reviewer_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def short_time(time)
   (Time.now.to_date - time).to_i
  end

  def poster_show(poster_path)
    "https://image.tmdb.org/t/p/w300_and_h450_bestv2" + poster_path
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/categories/index.html.erb
<div class="container">

  <!-- Page Header -->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">Movie Categories</h1>
    </div>
  </div>

  <!-- Projects Row -->
  <div class="row">
    <% @categories.each do |category| %>
      <div class="col-md-4 portfolio-item">
      <a href="<%= category_path(category) %>">
        <img class="img-responsive" src=<%= poster_show(category.movies.sample.poster_path) %> alt="">
        </a>
          <h3><%= link_to category.name, category_path(category) %></h3>
      </div>
    <% end %>
  </div>

  <br>
<!--
  <footer>
    <div class="row">
      <div class="col-lg-12">
        <p>Copyright © Killer Tomatoes 2016</p>
      </div>
    </div>
  </footer>
 -->
</div> <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

app/views/categories/show.html.erb
<main class="categories-group">


<!-- TOP 10 REVIEWS -->
<h2 class="category-title"><%= @category.name %></h2>
  <div class="container" style="float:left;width:71%">
<h2></h2>
    <% @category.movies.each do |movie| %>
      <div class="col-md-4">
      <%=link_to( image_tag(poster_show(movie.poster_path)), category_movie_path(@category, movie)) %>
      </div>
    <% end %>
  </div>


<!-- LIST OF MOVIE OF THE SAME CATEGORY -->
  <div class="top-review" style="width:25%; max-height:200%; margin-left:73%;">
  <h2 class="top-10-title">Top 10 reviews</h2>
    <% @category.reviews.recent.limit(10).each do |review| %>
      <div class="each-review">
        <%= link_to "#{review.movie.title}", category_movie_path(@category, review.movie) %><br>
        <%= link_to "#{review.title}", category_movie_path(@category, review.movie)  %><br>
        Review by: <%= review.reviewer.username  %>
      </div>
    <% end %>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieDatabase</title>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <!-- Latest compiled and minified CSS -->

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <%= csrf_meta_tags %>

</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Movie Reviews</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">

          <% if !user_signed_in? %>
            <li><%= link_to 'Log In', new_user_session_path %><span class="sr-only">(current)</span></li>
            <li><%= link_to 'Register', new_user_registration_path %></li>
          <% else %>
            <li><%= link_to "#{current_user.username}", current_user %><span class="sr-only">(current)</span></li>
            <li><%= link_to 'Log Out', destroy_user_session_path, :method => :delete %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">

          <div class="form-group">
          <%= form_tag movies_path, :method => 'get', :class => "navbar-form navbar-right" do %>
          <p>
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "Search", :name => nil %>
          </p>
          <% end %>
          </div>


<!--           <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form> -->
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <!-- Not sure about this really. Instructions are: "Ensure you have flash messages in app/views/layouts/application.html.erb" the following two lines are the examples provided -->
<div class="alert" style="visibility: hidden;">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>

  <%= yield %>

</body>
</html>

app/views/movies/index.html.erb
<!-- this is bootstrap -->
<div class="container">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Search Results
                    <small><%= @movies.length %> results</small>
                </h1>
            </div>
        </div>
        <!-- /.row -->
  <% if @errors %>
  <%= @errors %>
  <% else %>
  <% @movies.each do |movie| %>
        <div class="row">
            <div class="col-md-7">
                <a href="<%= movie_path(movie) %>">
                    <img id="search_img" class="img-responsive" src=<%=poster_show(movie.poster_path) %> alt=":(">
                </a>
            </div>
            <div class="col-md-5">
            <br><br><br><br>
                <h2><%= link_to movie.title, movie_path(movie) %></h2>
                <h3>Release Date: <%= movie.release_date.year %></h3>
                <p>Genre: <%= movie.category.name %></p>
            </div>
            </div>
            <br><br><br>
   <% end %>
  <%end %>



    </div>

app/views/movies/show.html.erb
<div class="container">

  <!-- new attempt -->

  <!-- end of new -->
  <div class="col-md-9">
    <div class="thumbnail">
      <img class="img-responsive" src=<%= poster_show(@movie.poster_path) %> alt="">

      <div class="caption-full">
        <h4><%= @movie.title %></h4>
        <p><%= @movie.summary %></p>
      </div>
      <div class="ratings">
        <p class="pull-right"><%= @movie.reviews.count %> reviews</p>
        <p>
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star-empty"></span>
          4.0 stars
        </p>
      </div>
    </div>
    </div>

      <div class="text-right">

      <%= button_to "Leave a review", new_movie_review_path(@movie.id), :class => "btn btn-success", :method => :get %>

      </div>

    <div class="well">
      <% @movie.reviews.recent.each do |review| %>
      <div class="row">

        <div class="vote">
          <div class="col-md-1 inline">
          <form class="button.up" action='/review_votes' method="post">
              <input type="hidden" name="vote[review_id]" value="<%= review.id %>">
              <input type="hidden" name="vote[voter_id]" value="<%= current_user.id %>">
              <input type="hidden" name="vote[vote_type]" value="true">
              <button class="up" type="submit" name="submit">
                <img src="http://clipartix.com/wp-content/uploads/2016/04/Thumbs-up-thumb-up-clip-art-clipart-2.png" height="20" width="20" alt="upvote_image">
              </button>
            </form>

            <form class="button.down" action='/categories/<%= "#{@movie.category_id}" %>/movies/<%= "#{@movie.id}" %>/reviews/vote' method="post">
              <input type="hidden" name="review_id" value="<%= review.id %>">
              <input type="hidden" name="vote_type" value="down">
              <button class="down" type="submit" name="submit">
                <img src="http://emojipedia-us.s3.amazonaws.com/cache/2f/3c/2f3c03f9e546e4d9652560347210ba9d.png" height="20" width="20" alt="down_vote_image">
              </button>
            </form>



          </div>

        <div class="col-md-11 inline">
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star-empty"></span>
          <%= link_to "#{review.reviewer.username}", user_path(review.reviewer) %>
          <br> Reviewer Status <%= review.reviewer.status %>
          <span class="pull-right"><%= short_time(review.created_at.to_date) %> days ago</span>
          <p><%= review.title %><br></p>
          <p><%= review.body %><br></p>

        </div>
      </div>
      <% end %>
    </div>

  </div>

</div>

app/views/reviews/_form.html.erb
<div class="field">
  <%= form_for [@movie, @review] do |f| %>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.label :title, class: "form-group" %>
    <%= f.hidden_field :movie_id, :value => @movie.id %>
    <%= f.hidden_field :reviewer_id, :value => current_user.id %>
    <%= f.hidden_field :reviewer_id, :value => current_user.id %>
    <%= f.text_field :title, class:"form-control" %><br>
    <%= f.label :Rating, class: "form-group" %>
    <%= f.select :stars, [1,2,3,4,5] %>
    <%= f.text_area :body, class: "form-control", rows: 5 %>
    <%= f.submit "Submit review", class: "btn btn-primary" %><br>
  <% end %><br>
</div>

app/views/reviews/_show.html.erb
<div class="row">
        <div class="col-md-12">
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star-empty"></span>
          <a href="/users/5"><%= @review.reviewer.username %></a>
          <span class="pull-right"><%= short_time(@review.created_at.to_date) %> days ago</span>
          <p><%= @review.title %><br></p>
          <p><%= @review.body %><br></p>
        </div>
</div>

app/views/reviews/new.html.erb
<div class="container">

<%= render 'form' %>

</div>

app/views/users/show.html.erb
<div class="container">

	<!-- Heading Row -->
	<div class="row">
		<div class="col-md-3">
			<% if @user.status == "Gold" %>
				<img class="img-responsive img-rounded" src="https://cdn0.iconfinder.com/data/icons/sport-balls/512/gold_medal.png" alt="">
			<% elsif @user.status == "Silver" %>
				<img class="img-responsive img-rounded" src="https://userscontent2.emaze.com/images/de83d5fa-2584-4fd6-a8a2-c3df85a908a1/94e277b35b521e8bfef0d840a52aceab.png" alt="">
			<% elsif @user.status == "Bronse" %>
				<img class="img-responsive img-rounded" src="https://cdn0.iconfinder.com/data/icons/sport-balls/512/bronze_medal.png" alt="">
			<% else %>
				<img class="img-responsive img-rounded" src="https://juancris13.files.wordpress.com/2014/03/muogho0.jpg" alt="">
			<% end %>

		</div>
		<!-- /.col-md-8 -->
		<div class="col-md-6">
			<h1>Hello <%= @user.username %></h1>
			<p>Thank you for being a <%= @user.status %> status reviewer.</p>
			<p>Reviews Written: <%= @user.reviews.count %></p>
		</div>
		<!-- /.col-md-4 -->
	</div>
	<!-- /.row -->

	<hr>

	<!-- Call to Action Well -->
	<div class="row">
		<div class="col-lg-12">
			<div class="text-center">
				<h1>Your reviews</h1>
				<br>
				<br>
			</div>
		</div>
		<!-- /.col-lg-12 -->
	</div>
	<!-- /.row -->
	<div class="container">
		<% @user.reviews.each do |review| %>
		<div class="well row">
			<div class="col-md-10">
				<h2><%= review.title %></h2>
				<p><%= review.body %></p>
				<p><%= review.points %> points</p>
			</div>
		</div>
		<br>

		<% end %>
	</div>
	<!-- Content Row -->


</div>